/**
 * @param {object} opts
 * @param {string} opts.serverName
 * @param {number} opts.mgmtPort
 */
export function renderServerConf(opts) {
  const lines = [
    "# Generated by hdc splunk package",
    "[general]",
    `serverName = ${opts.serverName}`,
    `mgmtHostPort = ${opts.mgmtPort}`,
    "",
  ];
  return lines.join("\n");
}

/**
 * @param {unknown[]} inputs
 */
export function renderInputsConf(inputs) {
  if (!inputs.length) {
    return "# Generated by hdc splunk package\n# No custom inputs configured.\n";
  }
  const lines = ["# Generated by hdc splunk package"];
  for (const raw of inputs) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) continue;
    const stanza = /** @type {Record<string, unknown>} */ (raw);
    const name = typeof stanza.name === "string" ? stanza.name.trim() : "";
    if (!name) continue;
    lines.push("", `[${name}]`);
    for (const [key, val] of Object.entries(stanza)) {
      if (key === "name") continue;
      if (val === undefined || val === null) continue;
      lines.push(`${key} = ${String(val)}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}
