/**
 * @param {string} s
 */
function yamlQuote(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

/**
 * @param {number} memoryMb
 */
export function jvmHeapMb(memoryMb) {
  const half = Math.floor(memoryMb / 2);
  const capped = Math.min(Math.max(half, 2048), 8192);
  return capped;
}

/**
 * @param {object} opts
 * @param {number} opts.memoryMb
 */
export function renderJvmOptions(opts) {
  const heap = jvmHeapMb(opts.memoryMb);
  return [
    "-XX:+UseG1GC",
    "-XX:+ParallelRefProcEnabled",
    "-XX:MaxGCPauseMillis=500",
    `-Xms${heap}m`,
    `-Xmx${heap}m`,
    "",
  ].join("\n");
}

/**
 * @param {object} opts
 * @param {string} opts.clusterName
 * @param {string[]} opts.seedIps
 * @param {string} opts.listenAddress
 * @param {boolean} opts.passwordAuthEnabled
 */
export function renderCassandraYaml(opts) {
  const seeds = opts.seedIps.join(",");
  const authLines = opts.passwordAuthEnabled
    ? [
        "authenticator: PasswordAuthenticator",
        "authorizer: CassandraAuthorizer",
        "role_manager: CassandraRoleManager",
      ]
    : [
        "authenticator: AllowAllAuthenticator",
        "authorizer: AllowAllAuthorizer",
      ];
  return [
    "# Generated by hdc cassandra package",
    `cluster_name: ${yamlQuote(opts.clusterName)}`,
    "",
    "seed_provider:",
    "  - class_name: org.apache.cassandra.locator.SimpleSeedProvider",
    "    parameters:",
    `      - seeds: ${yamlQuote(seeds)}`,
    "",
    `listen_address: ${opts.listenAddress}`,
    `rpc_address: ${opts.listenAddress}`,
    "listen_interface: null",
    "rpc_interface: null",
    "",
    "endpoint_snitch: GossipingPropertyFileSnitch",
    "auto_bootstrap: true",
    "start_native_transport: true",
    "native_transport_port: 9042",
    "",
    ...authLines,
    "",
    "hints_directory: /var/lib/cassandra/hints",
    "data_file_directories:",
    "  - /var/lib/cassandra/data",
    "commitlog_directory: /var/lib/cassandra/commitlog",
    "saved_caches_directory: /var/lib/cassandra/saved_caches",
    "",
  ].join("\n");
}

/**
 * @param {object} opts
 * @param {string} opts.datacenter
 * @param {string} opts.rack
 */
export function renderRackDcProperties(opts) {
  return [`dc=${opts.datacenter}`, `rack=${opts.rack}`, ""].join("\n");
}
