/**
 * @typedef {{ nodeId: number, host: string }} KafkaClusterNode
 */

/**
 * @param {KafkaClusterNode[]} nodes
 * @param {number} controllerPort
 */
export function buildControllerQuorumVoters(nodes, controllerPort) {
  return nodes
    .slice()
    .sort((a, b) => a.nodeId - b.nodeId)
    .map((n) => `${n.nodeId}@${n.host}:${controllerPort}`)
    .join(",");
}

/**
 * @param {object} opts
 * @param {number} opts.nodeId
 * @param {string} opts.clusterId
 * @param {string} opts.advertisedHost
 * @param {number} opts.listenerPort
 * @param {number} opts.controllerPort
 * @param {string} opts.quorumVoters
 * @param {string[]} opts.logDirs
 */
export function renderServerProperties(opts) {
  const logDirs = opts.logDirs.length ? opts.logDirs.join(",") : "/var/lib/kafka/data";
  const lines = [
    "# Generated by hdc kafka package",
    `node.id=${opts.nodeId}`,
    "process.roles=broker,controller",
    `cluster.id=${opts.clusterId}`,
    `controller.quorum.voters=${opts.quorumVoters}`,
    `listeners=PLAINTEXT://:${opts.listenerPort},CONTROLLER://:${opts.controllerPort}`,
    `advertised.listeners=PLAINTEXT://${opts.advertisedHost}:${opts.listenerPort}`,
    `controller.listener.names=CONTROLLER`,
    `listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT`,
    `inter.broker.listener.name=PLAINTEXT`,
    `log.dirs=${logDirs}`,
    "num.partitions=3",
    "default.replication.factor=3",
    "min.insync.replicas=2",
    "offsets.topic.replication.factor=3",
    "transaction.state.log.replication.factor=3",
    "transaction.state.log.min.isr=2",
    "auto.create.topics.enable=true",
    "",
  ];
  return lines.join("\n");
}

/**
 * @param {import("./deployments.mjs").ReturnType<import("./deployments.mjs").resolveAllKafkaDeployments>} deployments
 */
export function clusterNodesFromDeployments(deployments) {
  return deployments.map((d) => ({
    nodeId: d.nodeId,
    host: d.sshHost,
  }));
}
